/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.app.builder.it.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AppBuilderModule service. Represents a row in the &quot;AppBuilderModule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.app.builder.it.model.impl.AppBuilderModuleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.app.builder.it.model.impl.AppBuilderModuleImpl</code>.
 * </p>
 *
 * @author Marco Leo
 * @see AppBuilderModule
 * @generated
 */
@ProviderType
public interface AppBuilderModuleModel
	extends BaseModel<AppBuilderModule>, LocalizedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app builder module model instance should use the {@link AppBuilderModule} interface instead.
	 */

	/**
	 * Returns the primary key of this app builder module.
	 *
	 * @return the primary key of this app builder module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app builder module.
	 *
	 * @param primaryKey the primary key of this app builder module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this app builder module.
	 *
	 * @return the uuid of this app builder module
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this app builder module.
	 *
	 * @param uuid the uuid of this app builder module
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the app builder module ID of this app builder module.
	 *
	 * @return the app builder module ID of this app builder module
	 */
	public long getAppBuilderModuleId();

	/**
	 * Sets the app builder module ID of this app builder module.
	 *
	 * @param appBuilderModuleId the app builder module ID of this app builder module
	 */
	public void setAppBuilderModuleId(long appBuilderModuleId);

	/**
	 * Returns the company ID of this app builder module.
	 *
	 * @return the company ID of this app builder module
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this app builder module.
	 *
	 * @param companyId the company ID of this app builder module
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this app builder module.
	 *
	 * @return the user ID of this app builder module
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this app builder module.
	 *
	 * @param userId the user ID of this app builder module
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app builder module.
	 *
	 * @return the user uuid of this app builder module
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this app builder module.
	 *
	 * @param userUuid the user uuid of this app builder module
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this app builder module.
	 *
	 * @return the user name of this app builder module
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this app builder module.
	 *
	 * @param userName the user name of this app builder module
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this app builder module.
	 *
	 * @return the create date of this app builder module
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this app builder module.
	 *
	 * @param createDate the create date of this app builder module
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this app builder module.
	 *
	 * @return the modified date of this app builder module
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this app builder module.
	 *
	 * @param modifiedDate the modified date of this app builder module
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this app builder module.
	 *
	 * @return the active of this app builder module
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this app builder module is active.
	 *
	 * @return <code>true</code> if this app builder module is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this app builder module is active.
	 *
	 * @param active the active of this app builder module
	 */
	public void setActive(boolean active);

	/**
	 * Returns the name of this app builder module.
	 *
	 * @return the name of this app builder module
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this app builder module.
	 *
	 * @param name the name of this app builder module
	 */
	public void setName(String name);

	/**
	 * Returns the label of this app builder module.
	 *
	 * @return the label of this app builder module
	 */
	public String getLabel();

	/**
	 * Returns the localized label of this app builder module in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized label of this app builder module
	 */
	@AutoEscape
	public String getLabel(Locale locale);

	/**
	 * Returns the localized label of this app builder module in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this app builder module. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getLabel(Locale locale, boolean useDefault);

	/**
	 * Returns the localized label of this app builder module in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized label of this app builder module
	 */
	@AutoEscape
	public String getLabel(String languageId);

	/**
	 * Returns the localized label of this app builder module in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this app builder module
	 */
	@AutoEscape
	public String getLabel(String languageId, boolean useDefault);

	@AutoEscape
	public String getLabelCurrentLanguageId();

	@AutoEscape
	public String getLabelCurrentValue();

	/**
	 * Returns a map of the locales and localized labels of this app builder module.
	 *
	 * @return the locales and localized labels of this app builder module
	 */
	public Map<Locale, String> getLabelMap();

	/**
	 * Sets the label of this app builder module.
	 *
	 * @param label the label of this app builder module
	 */
	public void setLabel(String label);

	/**
	 * Sets the localized label of this app builder module in the language.
	 *
	 * @param label the localized label of this app builder module
	 * @param locale the locale of the language
	 */
	public void setLabel(String label, Locale locale);

	/**
	 * Sets the localized label of this app builder module in the language, and sets the default locale.
	 *
	 * @param label the localized label of this app builder module
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setLabel(String label, Locale locale, Locale defaultLocale);

	public void setLabelCurrentLanguageId(String languageId);

	/**
	 * Sets the localized labels of this app builder module from the map of locales and localized labels.
	 *
	 * @param labelMap the locales and localized labels of this app builder module
	 */
	public void setLabelMap(Map<Locale, String> labelMap);

	/**
	 * Sets the localized labels of this app builder module from the map of locales and localized labels, and sets the default locale.
	 *
	 * @param labelMap the locales and localized labels of this app builder module
	 * @param defaultLocale the default locale
	 */
	public void setLabelMap(Map<Locale, String> labelMap, Locale defaultLocale);

	/**
	 * Returns the db table name of this app builder module.
	 *
	 * @return the db table name of this app builder module
	 */
	@AutoEscape
	public String getDbTableName();

	/**
	 * Sets the db table name of this app builder module.
	 *
	 * @param dbTableName the db table name of this app builder module
	 */
	public void setDbTableName(String dbTableName);

	/**
	 * Returns the db table pk column name of this app builder module.
	 *
	 * @return the db table pk column name of this app builder module
	 */
	@AutoEscape
	public String getDbTablePKColumnName();

	/**
	 * Sets the db table pk column name of this app builder module.
	 *
	 * @param dbTablePKColumnName the db table pk column name of this app builder module
	 */
	public void setDbTablePKColumnName(String dbTablePKColumnName);

	/**
	 * Returns the scope of this app builder module.
	 *
	 * @return the scope of this app builder module
	 */
	@AutoEscape
	public String getScope();

	/**
	 * Sets the scope of this app builder module.
	 *
	 * @param scope the scope of this app builder module
	 */
	public void setScope(String scope);

	/**
	 * Returns the resource name of this app builder module.
	 *
	 * @return the resource name of this app builder module
	 */
	@AutoEscape
	public String getResourceName();

	/**
	 * Sets the resource name of this app builder module.
	 *
	 * @param resourceName the resource name of this app builder module
	 */
	public void setResourceName(String resourceName);

	/**
	 * Returns the asset of this app builder module.
	 *
	 * @return the asset of this app builder module
	 */
	public boolean getAsset();

	/**
	 * Returns <code>true</code> if this app builder module is asset.
	 *
	 * @return <code>true</code> if this app builder module is asset; <code>false</code> otherwise
	 */
	public boolean isAsset();

	/**
	 * Sets whether this app builder module is asset.
	 *
	 * @param asset the asset of this app builder module
	 */
	public void setAsset(boolean asset);

	/**
	 * Returns the resource of this app builder module.
	 *
	 * @return the resource of this app builder module
	 */
	public boolean getResource();

	/**
	 * Returns <code>true</code> if this app builder module is resource.
	 *
	 * @return <code>true</code> if this app builder module is resource; <code>false</code> otherwise
	 */
	public boolean isResource();

	/**
	 * Sets whether this app builder module is resource.
	 *
	 * @param resource the resource of this app builder module
	 */
	public void setResource(boolean resource);

	/**
	 * Returns the expando of this app builder module.
	 *
	 * @return the expando of this app builder module
	 */
	public boolean getExpando();

	/**
	 * Returns <code>true</code> if this app builder module is expando.
	 *
	 * @return <code>true</code> if this app builder module is expando; <code>false</code> otherwise
	 */
	public boolean isExpando();

	/**
	 * Sets whether this app builder module is expando.
	 *
	 * @param expando the expando of this app builder module
	 */
	public void setExpando(boolean expando);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}