/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.app.builder.it.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AppBuilderModuleField service. Represents a row in the &quot;AppBuilderModuleField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.app.builder.it.model.impl.AppBuilderModuleFieldModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.app.builder.it.model.impl.AppBuilderModuleFieldImpl</code>.
 * </p>
 *
 * @author Marco Leo
 * @see AppBuilderModuleField
 * @generated
 */
@ProviderType
public interface AppBuilderModuleFieldModel
	extends BaseModel<AppBuilderModuleField>, LocalizedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app builder module field model instance should use the {@link AppBuilderModuleField} interface instead.
	 */

	/**
	 * Returns the primary key of this app builder module field.
	 *
	 * @return the primary key of this app builder module field
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app builder module field.
	 *
	 * @param primaryKey the primary key of this app builder module field
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this app builder module field.
	 *
	 * @return the uuid of this app builder module field
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this app builder module field.
	 *
	 * @param uuid the uuid of this app builder module field
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the app builder module field ID of this app builder module field.
	 *
	 * @return the app builder module field ID of this app builder module field
	 */
	public long getAppBuilderModuleFieldId();

	/**
	 * Sets the app builder module field ID of this app builder module field.
	 *
	 * @param appBuilderModuleFieldId the app builder module field ID of this app builder module field
	 */
	public void setAppBuilderModuleFieldId(long appBuilderModuleFieldId);

	/**
	 * Returns the company ID of this app builder module field.
	 *
	 * @return the company ID of this app builder module field
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this app builder module field.
	 *
	 * @param companyId the company ID of this app builder module field
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this app builder module field.
	 *
	 * @return the user ID of this app builder module field
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this app builder module field.
	 *
	 * @param userId the user ID of this app builder module field
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app builder module field.
	 *
	 * @return the user uuid of this app builder module field
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this app builder module field.
	 *
	 * @param userUuid the user uuid of this app builder module field
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this app builder module field.
	 *
	 * @return the user name of this app builder module field
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this app builder module field.
	 *
	 * @param userName the user name of this app builder module field
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this app builder module field.
	 *
	 * @return the create date of this app builder module field
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this app builder module field.
	 *
	 * @param createDate the create date of this app builder module field
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this app builder module field.
	 *
	 * @return the modified date of this app builder module field
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this app builder module field.
	 *
	 * @param modifiedDate the modified date of this app builder module field
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the app builder module ID of this app builder module field.
	 *
	 * @return the app builder module ID of this app builder module field
	 */
	public long getAppBuilderModuleId();

	/**
	 * Sets the app builder module ID of this app builder module field.
	 *
	 * @param appBuilderModuleId the app builder module ID of this app builder module field
	 */
	public void setAppBuilderModuleId(long appBuilderModuleId);

	/**
	 * Returns the name of this app builder module field.
	 *
	 * @return the name of this app builder module field
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this app builder module field.
	 *
	 * @param name the name of this app builder module field
	 */
	public void setName(String name);

	/**
	 * Returns the label of this app builder module field.
	 *
	 * @return the label of this app builder module field
	 */
	public String getLabel();

	/**
	 * Returns the localized label of this app builder module field in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized label of this app builder module field
	 */
	@AutoEscape
	public String getLabel(Locale locale);

	/**
	 * Returns the localized label of this app builder module field in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this app builder module field. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getLabel(Locale locale, boolean useDefault);

	/**
	 * Returns the localized label of this app builder module field in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized label of this app builder module field
	 */
	@AutoEscape
	public String getLabel(String languageId);

	/**
	 * Returns the localized label of this app builder module field in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized label of this app builder module field
	 */
	@AutoEscape
	public String getLabel(String languageId, boolean useDefault);

	@AutoEscape
	public String getLabelCurrentLanguageId();

	@AutoEscape
	public String getLabelCurrentValue();

	/**
	 * Returns a map of the locales and localized labels of this app builder module field.
	 *
	 * @return the locales and localized labels of this app builder module field
	 */
	public Map<Locale, String> getLabelMap();

	/**
	 * Sets the label of this app builder module field.
	 *
	 * @param label the label of this app builder module field
	 */
	public void setLabel(String label);

	/**
	 * Sets the localized label of this app builder module field in the language.
	 *
	 * @param label the localized label of this app builder module field
	 * @param locale the locale of the language
	 */
	public void setLabel(String label, Locale locale);

	/**
	 * Sets the localized label of this app builder module field in the language, and sets the default locale.
	 *
	 * @param label the localized label of this app builder module field
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setLabel(String label, Locale locale, Locale defaultLocale);

	public void setLabelCurrentLanguageId(String languageId);

	/**
	 * Sets the localized labels of this app builder module field from the map of locales and localized labels.
	 *
	 * @param labelMap the locales and localized labels of this app builder module field
	 */
	public void setLabelMap(Map<Locale, String> labelMap);

	/**
	 * Sets the localized labels of this app builder module field from the map of locales and localized labels, and sets the default locale.
	 *
	 * @param labelMap the locales and localized labels of this app builder module field
	 * @param defaultLocale the default locale
	 */
	public void setLabelMap(Map<Locale, String> labelMap, Locale defaultLocale);

	/**
	 * Returns the db column name of this app builder module field.
	 *
	 * @return the db column name of this app builder module field
	 */
	@AutoEscape
	public String getDbColumnName();

	/**
	 * Sets the db column name of this app builder module field.
	 *
	 * @param dbColumnName the db column name of this app builder module field
	 */
	public void setDbColumnName(String dbColumnName);

	/**
	 * Returns the type of this app builder module field.
	 *
	 * @return the type of this app builder module field
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this app builder module field.
	 *
	 * @param type the type of this app builder module field
	 */
	public void setType(String type);

	/**
	 * Returns the type settings of this app builder module field.
	 *
	 * @return the type settings of this app builder module field
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this app builder module field.
	 *
	 * @param typeSettings the type settings of this app builder module field
	 */
	public void setTypeSettings(String typeSettings);

	/**
	 * Returns the nullable of this app builder module field.
	 *
	 * @return the nullable of this app builder module field
	 */
	public boolean getNullable();

	/**
	 * Returns <code>true</code> if this app builder module field is nullable.
	 *
	 * @return <code>true</code> if this app builder module field is nullable; <code>false</code> otherwise
	 */
	public boolean isNullable();

	/**
	 * Sets whether this app builder module field is nullable.
	 *
	 * @param nullable the nullable of this app builder module field
	 */
	public void setNullable(boolean nullable);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}